version: '3.1'

services:
  node:
    image: node:16
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm run start:dev"
    depends_on: 
      - mongodb
    ports:
      - 3000:3000
    links:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: uptime
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
